Text:
  LABELS:
    0: neutral
    1: happiness
    2: sadness
    3: enthusiasm
    4: fear
    5: anger
    6: disgust
Voice:
  labels:
    0: anger
    1: disgust
    2: enthusiasm
    3: fear
    4: happiness
    5: neutral
    6: sadness
  preprocess:
    audio-default-sample: 16000
    max-audio-duration-millis: 15000
Huggingface:
  wav2vec2_53_voice: Aniemore/wav2vec2-xlsr-53-russian-emotion-recognition
  rubert_tiny2_text: Aniemore/rubert-tiny2-russian-emotion-detection
YandexCloud:
  YC_FOLDER_ID: b1g75n4nfd17pefq9el4
  YC_IAM_TOKEN:
    created_at: 1653322904.0637176
    token: t1.9euelZqYms6PmpaRyYzOm4-Ky5CQxu3rnpWay52QiZWRlY6Oj8ySzsiOj4rl8_dnFlFr-e8LBnlZ_t3z9ydFTmv57wsGeVn-.oe5yj80S7ahqhI7DtK5bQHWXaJwJS3tWIGEbJ5OGRh2H9PPwrv54tACN0UYro8Y6aw6JiOU2na7U1I5uXtvxAg
  YC_URL: https://stt.api.cloud.yandex.net/speech/v1/stt:recognize
